// src/components/WelcomeMessage.jsx
// src/components/WelcomeMessage.jsx
import React, { useState, useEffect } from 'react';

const WelcomeMessage = () => {
  const [userName, setUserName] = useState('');

  useEffect(() => {
    // Obtener el nombre del usuario desde localStorage
    const storedName = localStorage.getItem('userName');
    if (storedName) {
      setUserName(storedName);
    }
  }, []);

  return (
    <div>
      {userName ? (
        <h1>¡Bienvenido, {userName}!</h1>
      ) : (
        <h1>Bienvenido!</h1>
      )}
    </div>
  );
};

export default WelcomeMessage;

// src/components/WelcomeMessage.vue
<!-- src/components/WelcomeMessage.vue -->
<template>
    <div>
      <h2>¡Bienvenido, {{ userName }}!</h2>
    </div>
  </template>
  
  <script setup>
  import { ref, onMounted } from 'vue';
  
  const userName = ref('');
  
  onMounted(() => {
    userName.value = localStorage.getItem('userName') || 'Usuario';
  });
  </script>
